use assert_cmd::Command;
use predicates::prelude::predicate;
use std::path::Path;

fn fixture_path() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("annotation-processor")
}

#[test]
fn annotation_processor_generates_code_and_runs() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let dest = tmp.path().join("project");

    fs_extra::dir::copy(
        fixture_path(),
        &dest,
        &fs_extra::dir::CopyOptions::new().content_only(true),
    )?;

    // Build — triggers annotation processing and generates source
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["build"]);
    cmd.assert().success();

    // Processor was compiled
    assert!(
        dest.join("target")
            .join("processor-bin")
            .join("processor")
            .join("MyProcessor.class")
            .exists(),
        "MyProcessor.class should exist after build"
    );

    // Generated source file was created by the annotation processor
    let generated_source = dest
        .join("target")
        .join("generated-source")
        .join("generated")
        .join("MyGeneratedClass.java");
    assert!(
        generated_source.exists(),
        "MyGeneratedClass.java should have been generated by annotation processing"
    );

    // Generated class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("generated")
            .join("MyGeneratedClass.class")
            .exists(),
        "MyGeneratedClass.class should exist after build"
    );

    // Main class was compiled
    assert!(
        dest.join("target").join("bin").join("Main.class").exists(),
        "Main.class should exist"
    );

    // Run the project and verify the generated code works
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["run", "--no-build", "Main"]);
    cmd.assert()
        .success()
        .stdout(predicate::str::contains("Hello from generated code!"));

    Ok(())
}
