use predicates::prelude::predicate;

use crate::support::{lazy_java, Project};

#[test]
fn annotation_processor_generates_code_and_runs() -> Result<(), Box<dyn std::error::Error>> {
    let p = Project::from_fixture("annotation-processor")?;
    let dest = &p.dir;

    // Build — triggers annotation processing and generates source
    lazy_java(dest)?.args(["build"]).assert().success();

    // Processor was compiled
    assert!(
        dest.join("target")
            .join("processor-bin")
            .join("processor")
            .join("MyProcessor.class")
            .exists(),
        "MyProcessor.class should exist after build"
    );

    // Generated source file was created by the annotation processor
    let generated_source = dest
        .join("target")
        .join("generated-source")
        .join("generated")
        .join("MyGeneratedClass.java");
    assert!(
        generated_source.exists(),
        "MyGeneratedClass.java should have been generated by annotation processing"
    );

    // Generated class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("generated")
            .join("MyGeneratedClass.class")
            .exists(),
        "MyGeneratedClass.class should exist after build"
    );

    // Main class was compiled
    assert!(
        dest.join("target").join("bin").join("Main.class").exists(),
        "Main.class should exist"
    );

    // Run the project and verify the generated code works
    lazy_java(dest)?
        .args(["run", "--no-build", "Main"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Hello from generated code!"));

    Ok(())
}