use assert_cmd::Command;
use predicates::prelude::predicate;
use std::path::Path;

fn fixture_path() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("auto-value")
}

#[test]
fn auto_value_generates_code_and_runs() -> Result<(), Box<dyn std::error::Error>> {
    let tmp = tempfile::tempdir()?;
    let dest = tmp.path().join("project");

    fs_extra::dir::copy(
        fixture_path(),
        &dest,
        &fs_extra::dir::CopyOptions::new().content_only(true),
    )?;

    // Step 1: Add the annotation dependency
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["add", "com.google.auto.value", "auto-value-annotations"]);
    cmd.assert().success();

    // Step 2: Add the annotation processor dependency
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["add", "com.google.auto.value", "auto-value"]);
    cmd.assert().success();

    assert!(
        dest.join("lazy-java.lock").exists(),
        "lock file should exist after add"
    );

    // Step 3: Build — triggers AutoValue annotation processing
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["build"]);
    cmd.assert().success();

    // Generated class was created by AutoValue
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("AutoValue_Person.class")
            .exists(),
        "AutoValue_Person.class should have been generated by annotation processing"
    );

    // Person class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("Person.class")
            .exists(),
        "Person.class should exist"
    );

    // Main class was compiled
    assert!(
        dest.join("target")
            .join("bin")
            .join("app")
            .join("Main.class")
            .exists(),
        "Main.class should exist"
    );

    // Step 4: Run and verify the generated code produces expected output
    let mut cmd = Command::cargo_bin("lazy-java")?;
    cmd.current_dir(&dest);
    cmd.args(["run", "--no-build", "app.Main"]);
    cmd.assert()
        .success()
        .stdout(predicate::str::contains("Alice"))
        .stdout(predicate::str::contains("30"));

    Ok(())
}
